export const filtredItems = [
  { id: 1, description: 'fspurdens0@ucla.edu', title: 'Spurdens' },
  { id: 2, description: 'fhenrys1@squarespace.com', title: 'Henrys' },
  {
    id: 3,
    description: 'jinchbald2@nationalgeographic.com',
    title: 'Inchbald',
  },
  { id: 4, description: 'dnajera3@sbwire.com', title: 'Najera' },
  { id: 5, description: 'ncaton4@tinyurl.com', title: 'Caton' },
  { id: 6, description: 'estove5@bloomberg.com', title: 'Stove' },
  { id: 7, description: 'gstabbins6@smugmug.com', title: 'Stabbins' },
  { id: 8, description: 'baudritt7@noaa.gov', title: 'Audritt' },
  { id: 9, description: 'adrawmer8@theguardian.com', title: 'Drawmer' },
  { id: 10, description: 'sdenham9@sfgate.com', title: 'Denham' },
  { id: 11, description: 'pdowdalla@theatlantic.com', title: 'Dowdall' },
  { id: 12, description: 'rlaydonb@51.la', title: 'Laydon' },
  { id: 13, description: 'iallibonec@addthis.com', title: 'Allibone' },
  { id: 14, description: 'spavlasekd@ed.gov', title: 'Pavlasek' },
  { id: 15, description: 'lwestcarre@t-online.de', title: 'Westcarr' },
  { id: 16, description: 'dwoodierf@quantcast.com', title: 'Woodier' },
  { id: 17, description: 'rgilluleyg@earthlink.net', title: 'Gilluley' },
  { id: 18, description: 'bjerransh@huffingtonpost.com', title: 'Jerrans' },
  { id: 19, description: 'mtaxi@cdc.gov', title: 'Tax' },
  { id: 20, description: 'mduffanj@bing.com', title: 'Duffan' },
]
